rules = [
  OrganizeImports,
  DisableSyntax,
  LeakingImplicitClassVal,
  NoValInForComprehension,
  RedundantSyntax
]

OrganizeImports {
  coalesceToWildcardImportThreshold = 3
  expandRelative = false
  groupExplicitlyImportedImplicitsSeparately = false
  groupedImports = AggressiveMerge
  groups = [
    "re:javax?\\."
    "scala."
    "*"
    "com.serenity."
  ]
  importSelectorsOrder = Ascii
  importsOrder = Ascii
  preset = DEFAULT
  removeUnused = true
}

DisableSyntax {
  noVars = true
  noNulls = false
  noReturns = true
  noWhileLoops = true
  noAsInstanceOf = false
  noIsInstanceOf = false
  noXml = true
  noDefaultArgs = false
  noFinalVal = true
  noFinalize = true
  regex = []
}

RemoveUnused {
  imports = true
  privates = true
  locals = true
  patternvars = true
}