import java.nio.charset.StandardCharsets
import java.nio.file.{Files, Path}

import scala.collection.JavaConverters.*

/** Renders THIRD-PARTY-NOTICES.md from the resolved runtime classpath and the hand-curated registry under
  * `third-party/`.
  *
  * The registry is the point: a module the build resolves but the registry does not know has no licence entry, and
  * rendering fails naming it (#2019). Versions come from the classpath, so a bump needs no registry edit; a new
  * dependency, or a renamed artifact, does.
  */
object ThirdPartyNotices {

  final case class Module(organization: String, name: String, version: String) {
    def key: String = s"$organization:$name"
  }

  private final case class Entry(
      title: String,
      version: String,
      licence: String,
      texts: List[String],
      copyright: String,
      url: String
  )

  def render(root: Path, runtimeModules: Seq[Module]): Either[String, String] = {
    val registry = registryRows(root.resolve("third-party").resolve("modules.tsv"))
    val unknown  = runtimeModules.map(_.key).distinct.filterNot(key => registry.exists(_.head == key))
    if (unknown.nonEmpty)
      Left(
        s"""Runtime modules without a licence entry in third-party/modules.tsv:
           |${unknown.sorted.map("  " + _).mkString("\n")}
           |Add a row for each (licence, texts under third-party/texts, copyright, url) after checking its licence is GPL-3.0-or-later compatible.""".stripMargin
      )
    else {
      val modules = runtimeModules.groupBy(_.key).values.map(_.head).toList.sortBy(_.key)
      val entries = modules.flatMap { module =>
        registry.find(_.head == module.key).map { row =>
          Entry(module.key, module.version, row(1), textIds(row(2)), row(3), row(4))
        }
      }
      val assets = registryRows(root.resolve("third-party").resolve("assets.tsv")).map { row =>
        Entry(row.head, row(1), row(2), textIds(row(3)), row(4), row(5))
      }
      Right(document(root, entries, assets))
    }
  }

  def runtimeModulesOf(
      classpath: Seq[sbt.Attributed[java.io.File]]
  ): Seq[Module] =
    classpath.flatMap(_.get(sbt.Keys.moduleID.key)).map(id => Module(id.organization, id.name, id.revision))

  private def textIds(column: String): List[String] =
    column.split(",").toList.map(_.trim).filter(_.nonEmpty)

  private def registryRows(file: Path): List[Array[String]] =
    Files
      .readAllLines(file, StandardCharsets.UTF_8)
      .asScala
      .toList
      .filterNot(line => line.trim.isEmpty || line.startsWith("#"))
      .map(_.split("\t", -1))

  private def textFile(root: Path, id: String): Path =
    if (id.contains("/")) root.resolve(id) else root.resolve("third-party").resolve("texts").resolve(id + ".txt")

  private def textTitle(id: String): String =
    id.substring(id.lastIndexOf('/') + 1).stripSuffix(".txt")

  private def readText(root: Path, id: String): String =
    new String(Files.readAllBytes(textFile(root, id)), StandardCharsets.UTF_8).replace("\r\n", "\n").trim

  private def document(root: Path, modules: List[Entry], assets: List[Entry]): String = {
    val textIdsUsed = (modules ++ assets).flatMap(_.texts).distinct.sortBy(textTitle)
    val header =
      """# Third-party notices
        |
        |Serenity is licensed under the GNU General Public License, version 3 or (at your option) any later version
        |(see `LICENSE`). It includes the third-party software and assets below, each under its own licence.
        |Where a component is offered under a choice of licences, the licence column names the one Serenity uses.
        |
        |This file is generated by `sbt generateThirdPartyNotices` from the resolved runtime classpath and the registry
        |in `third-party/`. Do not edit it by hand: `sbt checkThirdPartyNotices` fails when it is out of date.
        |
        |""".stripMargin
    val moduleTable = table("## Runtime libraries", modules)
    val assetTable  = table("## Bundled assets", assets)
    val texts = textIdsUsed
      .map(id => s"### ${textTitle(id)}\n\n```text\n${readText(root, id)}\n```\n")
      .mkString("\n")
    header + moduleTable + "\n" + assetTable + "\n## Licence and notice texts\n\n" + texts
  }

  private def table(heading: String, entries: List[Entry]): String = {
    val rows = entries.map { e =>
      val version = if (e.version.isEmpty) "-" else e.version
      val texts   = e.texts.map(textTitle).mkString(", ")
      s"| ${e.title} | $version | ${e.licence} | ${e.copyright} | <${e.url}> | ${if (texts.isEmpty) "-" else texts} |"
    }
    (Seq(
      heading,
      "",
      "| Component | Version | Licence | Copyright | URL | Texts |",
      "| --- | --- | --- | --- | --- | --- |"
    ) ++ rows).mkString("\n") + "\n"
  }
}
