package com.serenity.config

import java.nio.file.Paths

import org.scalatest.OptionValues
import org.scalatest.flatspec.AnyFlatSpec
import org.scalatest.matchers.should.Matchers

class ConfigMigrationWarningSpec extends AnyFlatSpec with Matchers with OptionValues:

  "ConfigMigrationWarning" should "format actionable startup warnings" in {
    val report = ConfigMigrationReport(
      version = ConfigVersion.Current,
      deprecatedEntries = List(DeprecatedConfigEntry("cursor_mode", "cursor.mode")),
      unknownKeys = List("custom.old"),
      invalidEntries = List(InvalidConfigEntry("syntax.highlighting", "maybe", "Invalid boolean"))
    )

    val message = ConfigMigrationWarning.message(Paths.get("config.conf"), report).value

    message should include("[CONFIG] Deprecated config format detected in config.conf.")
    message should include("- cursor_mode -> use cursor.mode")
    message should include("Unknown entries:")
    message should include("- custom.old")
    message should include("Invalid entries:")
    message should include("- syntax.highlighting = maybe (Invalid boolean)")
    message should include("Suggested upgraded config can be generated by saving settings from Serenity.")
  }

  it should "return no message for an empty report" in {
    ConfigMigrationWarning.message(Paths.get("config.conf"), ConfigMigrationReport.empty) shouldBe None
  }
