package com.serenity.config

import java.nio.file.Path

case class ConfigVersion(value: Int) extends AnyVal:
  override def toString: String = value.toString

object ConfigVersion:
  val Current: ConfigVersion = ConfigVersion(1)

case class DeprecatedConfigEntry(
    key: String,
    replacement: String
)

case class InvalidConfigEntry(
    key: String,
    value: String,
    reason: String
)

case class ConfigMigrationReport(
    version: ConfigVersion,
    deprecatedEntries: List[DeprecatedConfigEntry] = Nil,
    unknownKeys: List[String] = Nil,
    invalidEntries: List[InvalidConfigEntry] = Nil,
    defaultedKeys: List[String] = Nil
):
  def hasWarnings: Boolean =
    deprecatedEntries.nonEmpty || unknownKeys.nonEmpty || invalidEntries.nonEmpty

object ConfigMigrationReport:
  val empty: ConfigMigrationReport = ConfigMigrationReport(ConfigVersion.Current)

case class ConfigLoadResult(
    config: AppConfig,
    report: ConfigMigrationReport
)

object ConfigMigrationWarning:

  def message(path: Path, report: ConfigMigrationReport): Option[String] =
    Option.when(report.hasWarnings) {
      val deprecated =
        section(
          "Deprecated entries:",
          report.deprecatedEntries.map(entry => s"- ${entry.key} -> use ${entry.replacement}")
        )
      val unknown =
        section(
          "Unknown entries:",
          report.unknownKeys.map(key => s"- $key")
        )
      val invalid =
        section(
          "Invalid entries:",
          report.invalidEntries.map(entry => s"- ${entry.key} = ${entry.value} (${entry.reason})")
        )

      List(
        Some(s"[CONFIG] Deprecated config format detected in $path."),
        deprecated,
        unknown,
        invalid,
        Some("Suggested upgraded config can be generated by saving settings from Serenity.")
      ).flatten.mkString("\n")
    }

  private def section(title: String, lines: List[String]): Option[String] =
    Option.when(lines.nonEmpty)((title :: lines).mkString("\n"))
